In [236]:
import os
import csv
import pandas as pd

In [237]:
#Create a csv with the initial columnnames
import csv
with open('/Users/laurabreimann/Desktop/Inga/database/smFISH_database.csv', 'w', newline='') as table:
    fieldnames = ["filename",'folder',"target", "count", ]
    writer = csv.DictWriter(table, fieldnames=fieldnames)
    writer.writeheader()

In [238]:
# This is the path where you want to search
path ='/Users/laurabreimann/Desktop/Inga/best_results/'
csv_file= '/Users/laurabreimann/Desktop/Inga/database/smFISH_database.csv'


# this is the extension you want to detect
extension = '.csv'

length_of_file = []



for root, dirs_list, files_list in os.walk(path):
    for file_name in files_list:
        if file_name[-4:] == extension and not file_name.startswith('._'):
            #print(os.path.join(root, file_name))
            reader = pd.read_csv(os.path.join(root, file_name))
            length_of_file = len(reader)
           
            with open(csv_file, 'a', newline='') as file:
                fieldnames = ["filename","folder","target","count"]
                writer = csv.DictWriter(file, fieldnames=fieldnames, delimiter=',',lineterminator='\n')
                writer.writerow({"filename": file_name, "folder": root, "count" : length_of_file })

In [239]:
df = pd.read_csv('/Users/laurabreimann/Desktop/Inga/database/smFISH_database.csv')

In [240]:
df.head()

,filename,folder,target,count
0,ActB_Puro_Map2_scr15.csv,/Users/laurabreimann/Desktop/Inga/best_results/,NaN,89
1,ActB_Puro_Map2_scr14.csv,/Users/laurabreimann/Desktop/Inga/best_results/,NaN,47
2,ActB_Puro_Map2_scr16.csv,/Users/laurabreimann/Desktop/Inga/best_results/,NaN,87
3,ActB_Puro_Map2_scr17.csv,/Users/laurabreimann/Desktop/Inga/best_results/,NaN,82
4,ActB_Puro_Map2_scr19_1.csv,/Users/laurabreimann/Desktop/Inga/best_results/,NaN,15

In [241]:
# Create a column with the shRNA condition 

df.loc[df['filename'].str.contains('larp'), 'shRNA'] = 'shLarp'
df.loc[df['filename'].str.contains('scr'), 'shRNA'] = 'ctrl'

In [242]:
#sort the database
df.sort_values(
    by=["shRNA","filename"])

df.head(5)

,filename,folder,target,count,shRNA
0,ActB_Puro_Map2_scr15.csv,/Users/laurabreimann/Desktop/Inga/best_results/,NaN,89,ctrl
1,ActB_Puro_Map2_scr14.csv,/Users/laurabreimann/Desktop/Inga/best_results/,NaN,47,ctrl
2,ActB_Puro_Map2_scr16.csv,/Users/laurabreimann/Desktop/Inga/best_results/,NaN,87,ctrl
3,ActB_Puro_Map2_scr17.csv,/Users/laurabreimann/Desktop/Inga/best_results/,NaN,82,ctrl
4,ActB_Puro_Map2_scr19_1.csv,/Users/laurabreimann/Desktop/Inga/best_results/,NaN,15,ctrl

In [243]:
len(df)

80

In [244]:
df.to_csv('/Users/laurabreimann/Desktop/Inga/database/smFISH_database_2.csv', index=False)

In [245]:
#read in the area of the structures

#Create a csv with the initial columnnames
import csv
with open('/Users/laurabreimann/Desktop/Inga/database/area_sizes.csv', 'w', newline='') as table:
    fieldnames = ["filename",'area', "folder"]
    writer = csv.DictWriter(table, fieldnames=fieldnames)
    writer.writeheader()

In [246]:
# This is the path where you want to search
path_area ='/Users/laurabreimann/Desktop/Inga/masks/mask_size/'
area_file= '/Users/laurabreimann/Desktop/Inga/database/area_sizes.csv'


# this is the extension you want to detect
extension = '.csv'

size_of_mask = []



for root, dirs_list, files_list in os.walk(path_area):
    for file_name in files_list:
        if file_name[-4:] == extension and not file_name.startswith('._'):
            #print(os.path.join(root, file_name))
            reader = pd.read_csv(os.path.join(root, file_name))
            size_of_mask = float(reader['Area'])
           
            with open(area_file, 'a', newline='') as file:
                fieldnames = ["filename",'area', "folder"]
                writer = csv.DictWriter(file, fieldnames=fieldnames, delimiter=',',lineterminator='\n')
                writer.writerow({"filename": file_name, "folder": root, "area":  size_of_mask   })

In [247]:
area_csv = pd.read_csv('/Users/laurabreimann/Desktop/Inga/database/area_sizes.csv')

area_csv.loc[area_csv['filename'].str.contains('larp'), 'shRNA'] = 'shLarp'
area_csv.loc[area_csv['filename'].str.contains('scr'), 'shRNA'] = 'ctrl'

area_csv.sort_values(
    by=["shRNA", "filename"])
area_csv.head(5)

,filename,area,folder,shRNA
0,ActB_Puro_Map2_larp25_1.tif.csv,1158.4154,/Users/laurabreimann/Desktop/Inga/masks/mask_s...,shLarp
1,ActB_Puro_Map2_scr21.tif.csv,633.2325,/Users/laurabreimann/Desktop/Inga/masks/mask_s...,ctrl
2,ActB_Puro_Map2_scr2_1.tif.csv,582.1120,/Users/laurabreimann/Desktop/Inga/masks/mask_s...,ctrl
3,ActB_Puro_Map2_scr5_3.tif.csv,942.9079,/Users/laurabreimann/Desktop/Inga/masks/mask_s...,ctrl
4,ActB_Puro_Map2_scr10_1.tif.csv,457.5319,/Users/laurabreimann/Desktop/Inga/masks/mask_s...,ctrl

In [248]:
len(area_csv)

80

In [249]:
### Combine the two datasets
split_word = '.csv'
df['id'] = df.filename.str.partition(split_word)[0]
df.head()
#df.to_csv('/Users/laurabreimann/Desktop/Inga/database/smFISH_database_3.csv', index=False)

,filename,folder,target,count,shRNA,id
0,ActB_Puro_Map2_scr15.csv,/Users/laurabreimann/Desktop/Inga/best_results/,NaN,89,ctrl,ActB_Puro_Map2_scr15
1,ActB_Puro_Map2_scr14.csv,/Users/laurabreimann/Desktop/Inga/best_results/,NaN,47,ctrl,ActB_Puro_Map2_scr14
2,ActB_Puro_Map2_scr16.csv,/Users/laurabreimann/Desktop/Inga/best_results/,NaN,87,ctrl,ActB_Puro_Map2_scr16
3,ActB_Puro_Map2_scr17.csv,/Users/laurabreimann/Desktop/Inga/best_results/,NaN,82,ctrl,ActB_Puro_Map2_scr17
4,ActB_Puro_Map2_scr19_1.csv,/Users/laurabreimann/Desktop/Inga/best_results/,NaN,15,ctrl,ActB_Puro_Map2_scr19_1

In [250]:
split_word = '.tif'
area_csv['id'] = area_csv['filename'].str.partition(split_word)[0]
area_csv.head()

,filename,area,folder,shRNA,id
0,ActB_Puro_Map2_larp25_1.tif.csv,1158.4154,/Users/laurabreimann/Desktop/Inga/masks/mask_s...,shLarp,ActB_Puro_Map2_larp25_1
1,ActB_Puro_Map2_scr21.tif.csv,633.2325,/Users/laurabreimann/Desktop/Inga/masks/mask_s...,ctrl,ActB_Puro_Map2_scr21
2,ActB_Puro_Map2_scr2_1.tif.csv,582.1120,/Users/laurabreimann/Desktop/Inga/masks/mask_s...,ctrl,ActB_Puro_Map2_scr2_1
3,ActB_Puro_Map2_scr5_3.tif.csv,942.9079,/Users/laurabreimann/Desktop/Inga/masks/mask_s...,ctrl,ActB_Puro_Map2_scr5_3
4,ActB_Puro_Map2_scr10_1.tif.csv,457.5319,/Users/laurabreimann/Desktop/Inga/masks/mask_s...,ctrl,ActB_Puro_Map2_scr10_1

In [251]:
area_csv.to_csv('/Users/laurabreimann/Desktop/Inga/database/area_sizes_2.csv', index=False)

In [252]:
area_id = area_csv.filter(['area', 'id', 'shRNA'], axis = 1)
area_id.head(5)

        area                       id   shRNA
0  1158.4154  ActB_Puro_Map2_larp25_1  shLarp
1   633.2325     ActB_Puro_Map2_scr21    ctrl
2   582.1120    ActB_Puro_Map2_scr2_1    ctrl
3   942.9079    ActB_Puro_Map2_scr5_3    ctrl
4   457.5319   ActB_Puro_Map2_scr10_1    ctrl

In [253]:
df = df.filter(['count', 'id', 'shRNA'], axis = 1)
df.head()

   count                      id shRNA
0     89    ActB_Puro_Map2_scr15  ctrl
1     47    ActB_Puro_Map2_scr14  ctrl
2     87    ActB_Puro_Map2_scr16  ctrl
3     82    ActB_Puro_Map2_scr17  ctrl
4     15  ActB_Puro_Map2_scr19_1  ctrl

In [254]:
df3 = df.merge(area_csv[['id', 'area']], on = ['id'], how = 'outer')
df3.head(5)

   count                      id shRNA       area
0     89    ActB_Puro_Map2_scr15  ctrl  1592.9277
1     47    ActB_Puro_Map2_scr14  ctrl   827.0924
2     87    ActB_Puro_Map2_scr16  ctrl  1352.9030
3     82    ActB_Puro_Map2_scr17  ctrl  1420.6168
4     15  ActB_Puro_Map2_scr19_1  ctrl   458.5004

In [255]:
df3['smFISH_per_area'] = df3['count']/df3['area']
df3.head(5)

   count                      id shRNA       area  smFISH_per_area
0     89    ActB_Puro_Map2_scr15  ctrl  1592.9277         0.055872
1     47    ActB_Puro_Map2_scr14  ctrl   827.0924         0.056826
2     87    ActB_Puro_Map2_scr16  ctrl  1352.9030         0.064306
3     82    ActB_Puro_Map2_scr17  ctrl  1420.6168         0.057721
4     15  ActB_Puro_Map2_scr19_1  ctrl   458.5004         0.032715

In [256]:
len(df3)

80

In [257]:
df3.to_csv('/Users/laurabreimann/Desktop/Inga/database/total_database.csv', index=False)